name: Test DepremOpenAiApi

on:
  push:
    branches-ignore: ["main"]

env:
  OPENAI_API_BASE_POOL: ${{ secrets.OPENAI_API_BASE_POOL }}
  OPENAI_API_KEY_POOL: ${{ secrets.OPENAI_API_KEY_POOL }}
  NEEDS_RESOLVER_API_KEY: ${{ secrets.NEEDS_RESOLVER_API_KEY }}

jobs:
  deploy:
    name: test_on_branch
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and test
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t deprem-openai-apis-test:latest .
          docker run --rm -t deprem-openai-apis-test:latest sh -c "NEEDS_RESOLVER_API_KEY=${NEEDS_RESOLVER_API_KEY} OPENAI_API_BASE_POOL=${OPENAI_API_BASE_POOL} OPENAI_API_KEY_POOL=${OPENAI_API_KEY_POOL} pytest --verbose -s"
