name: Test DepremOpenAiApi

on:
  push:
    branches-ignore: ["main"]

env:
  OPENAI_API_BASE_POOL: ${{ secrets.OPENAI_API_BASE_POOL }}
  OPENAI_API_KEY_POOL: ${{ secrets.OPENAI_API_KEY_POOL }}

jobs:
  deploy:
    name: test_on_branch
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install deps
      run: python -m pip install -r requirements.txt
    - name: Tests
      run: |
        OPENAI_API_BASE_POOL=${OPENAI_API_BASE_POOL} OPENAI_API_KEY_POOL=${OPENAI_API_KEY_POOL} pytest --verbose